name: Code Checks
on: push
jobs:

  test-python-versions:
    name: Check Python ${{matrix.python-version}} on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
        allow_failure: [false]
        include:
          - python-version: "3.12.0-beta.4"
            allow_failure: true
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Install package
        run: python -m pip install -e .[test]

      - name: Test package
        run: python -m pytest
